version: "2.2"
services:
  web01:
    image: nginx
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
  file01:

  redis01:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
  

  ha-proxy:
    image: haproxy:1.7
    volumes:
      - './haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'

  db01:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - db.env
    volumes:
        - './db01-data:/var/lib/mysql'
  
  db02:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - db.env
    volumes:
      - './db02-data:/var/lib/mysql'


