version: '3.8'
services:
  app:
    image: netzint/nextcloud-fpm:25.0.3
  fpm01:
    image: netzint/nextcloud-fpm:25.0.3
  fpm02:
    image: netzint/nextcloud-fpm:25.0.3
  fpm03:
    image: netzint/nextcloud-fpm:25.0.3
  fpm04:
    image: netzint/nextcloud-fpm:25.0.3

