version: "3.8"
services:
  nc-web01:
    image: nginx
    ports:
      - 9080:80
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud: {}

  nc-web02:
    image: nginx
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud: {}


  nc-web03:
    image: nginx
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud: {}


  nc-web04:
    image: nginx
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
      - ./nextcloud:/var/www/nextcloud:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud: {}
    
  nc-proxy01:
    image: haproxy:2.3
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - './nc-proxy/haproxy:/usr/local/etc/haproxy/haproxy.cfg'
      - './nc-proxy/webserver:/etc/ssl/webserver'
    networks:
      nextcloud: {}

  


  redis01:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm
    links:
      - nc-sqlbroker
    volumes:
      - ./nextcloud:/var/www/html
    restart: always
    networks:
      nextcloud: {}
  

  nc-sqlbroker:
    image: haproxy:2.3
    volumes:
      - './nc-sqlbroker/haproxy/:/usr/local/etc/haproxy'
    networks:
      nextcloud: {}
  

  nc-db01:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - db.env
    volumes:
        - './db01-data:/var/lib/mysql'
    networks:
      nextcloud: {}
  
  nc-db02:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - db.env
    volumes:
      - './db02-data:/var/lib/mysql'
    networks:
      nextcloud: {}

networks:
  nextcloud:
    external: true
    name: nextcloud
    driver: overlay

volumes:
  nextcloud:
  nc-sqlbroker:
      
      


