version: "3.8"
services:
  nc-web01:
    image: nginx
    ports:
      - 9080:80
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.11

  nc-web02:
    image: nginx
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.12


  nc-web03:
    image: nginx
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.13


  nc-web04:
    image: nginx
    links:
      - app
    volumes:
      - ./web/nextcloud:/etc/nginx/conf.d/default.conf:ro
      - ./nextcloud:/var/www/nextcloud:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.14
    
  nc-proxy01:
    image: haproxy:2.3
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - './nc-proxy/haproxy:/usr/local/etc/haproxy/haproxy.cfg'
      - './nc-proxy/webserver:/etc/ssl/webserver'
    networks:
      nextcloud:
        ipv4_address: 172.24.0.4

  

  redis01:
    image: redis:alpine
    restart: always
    networks:
      nextcloud: {}

  app:
    image: nextcloud:fpm
    links:
      - nc-sqlbroker
    volumes:
      - ./nextcloud/data:/var/www/html/data
    restart: always
    environment:
      - MYSQL_HOST=nc-sqlbroker
      - REDIS_HOST=redis01
      - TRUSTED_PROXIES=174.24.0.4
    env_file:
      - db.env
    networks:
      nextcloud: {}
  

  nc-sqlbroker:
    image: haproxy:2.3
    volumes:
      - './nc-sqlbroker/haproxy:/usr/local/etc/haproxy/haproxy.cfg'
    networks:
      nextcloud: {}
  

  nc-db01:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    env_file:
      - db.env
    volumes:
        - './db01-data:/var/lib/mysql'
    networks:
      nextcloud:
        ipv4_address: 172.24.0.100
  
  nc-db02:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    env_file:
      - db.env
    volumes:
      - './db02-data:/var/lib/mysql'
    networks:
      nextcloud:
        ipv4_address: 172.24.0.101

networks:
  nextcloud:
    external: true
    name: nextcloud
    driver: overlay

volumes:
  nextcloud:
  nc-sqlbroker:
      
      


