version: "3.8"
services:

  nc-web01:
    image: nginx
    links:
      - app
    volumes:
      - ./web/web01/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.11

  nc-web02:
    image: nginx
    links:
      - app
    volumes:
      - ./web/web02/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.12

  nc-web03:
    image: nginx
    links:
      - app
    volumes:
      - ./web/web03/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.13

  nc-web04:
    image: nginx
    links:
      - app
    volumes:
      - ./web/web04/nextcloud.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - app
    restart: always
    depends_on: 
      - app
    networks:
      nextcloud:
        ipv4_address: 172.24.0.14
    
  nc-proxy01:
    image: haproxy:2.3
    ports:
      - 443:443
    volumes:
      - './nc-proxy/haproxy:/usr/local/etc/haproxy/haproxy.cfg'
      - './nc-proxy/webserver:/etc/ssl/webserver'
    networks:
      nextcloud:
        ipv4_address: 172.24.0.4

  redis01:
    image: redis:alpine
    command: redis-server --requirepass redis2020passwordImportant
    restart: always
    networks:
      nextcloud:
        ipv4_address: 172.24.0.5

  app:
    image: netzint/nextcloud-fpm
    volumes:
      - ./nextcloud-persistant/data:/var/www/html/data
      - ./nextcloud-persistant/custom_apps:/var/www/html/custom_apps
      - ./nextcloud-persistant/config:/var/www/html/config
    restart: always
    env_file:
      - db.env
    networks:
      nextcloud:
        ipv4_address: 172.24.0.30

  fpm01:
    image: netzint/nextcloud-fpm
    restart: always
    volumes_from:
      - app
    env_file:
      - db.env
    environment:
      - NEXTCLOUD_ENABLE_CRON=0
    networks:
      nextcloud:
        ipv4_address: 172.24.0.31
        
  fpm02:
    image: netzint/nextcloud-fpm
    restart: always
    volumes_from:
      - app
    env_file:
      - db.env
    environment:
      - NEXTCLOUD_ENABLE_CRON=0
    networks:
      nextcloud:
        ipv4_address: 172.24.0.32

  fpm03:
    image: netzint/nextcloud-fpm
    restart: always
    volumes_from:
      - app
    env_file:
      - db.env
    environment:
      - NEXTCLOUD_ENABLE_CRON=0
    networks:
      nextcloud:
        ipv4_address: 172.24.0.33

  fpm04:
    image: netzint/nextcloud-fpm
    restart: always
    volumes_from:
      - app
    env_file:
      - db.env
    environment:
      - NEXTCLOUD_ENABLE_CRON=0
    networks:
      nextcloud:
        ipv4_address: 172.24.0.34

  nc-sqlbroker:
    image: haproxy:2.3
    restart: always
    volumes:
      - './nc-sqlbroker/haproxy:/usr/local/etc/haproxy/haproxy.cfg'
    ports:
      - 3306:3306
    networks:
      nextcloud:
        ipv4_address: 172.24.0.7

  nc-db01:
    image: mariadb:10.5.8
    command: >
          --transaction-isolation=READ-COMMITTED 
          --binlog-format=ROW 
          --innodb-large-prefix=on
          --innodb-file-per-table=1
          --innodb_file_format=barracuda 
          --wsrep-on=ON 
          --wsrep-provider=/usr/lib/galera/libgalera_smm.so 
          --wsrep-cluster-address="gcomm://172.24.0.100,172.24.0.101" 
          --default-storage-engine=InnoDB 
          --innodb-autoinc-lock-mode=2
          --innodb-force-primary-key=1 
          --innodb-doublewrite=1 
          --wsrep-cluster-name=NextcloudCluster 
          --wsrep-node-name=nc-db01 
          --wsrep-node-address="172.24.0.100"
          --innodb-flush-log-at-trx-commit=2
          --wsrep-new-cluster
          --max_allowed_packet=128M
          --skip_name_resolve=1
          --innodb_buffer_pool_size=128M
          --innodb_buffer_pool_instances=1
          --innodb_log_buffer_size=32M
          --innodb_max_dirty_pages_pct=90
          --query_cache_type=1
          --query_cache_limit=2M
          --query_cache_min_res_unit=2k
          --query_cache_size=64M
          --tmp_table_size=64M
          --max_heap_table_size=64M
          --slow_query_log=1
          --long_query_time=1
          --wait_timeout=30
    restart: always
    env_file:
      - db.env
    volumes:
        - './db01-data:/var/lib/mysql'
    networks:
      nextcloud:
        ipv4_address: 172.24.0.100
  
  nc-db02:
    image: mariadb:10.5.8
    command: >
          --transaction-isolation=READ-COMMITTED
          --binlog-format=ROW
          --innodb-large-prefix=on
          --innodb-file-per-table=1
          --innodb_file_format=barracuda
          --wsrep-on=ON
          --wsrep-provider=/usr/lib/galera/libgalera_smm.so
          --wsrep-cluster-address="gcomm://172.24.0.100,172.24.0.101"
          --default-storage-engine=InnoDB
          --innodb-autoinc-lock-mode=2
          --innodb-force-primary-key=1
          --innodb-doublewrite=1
          --wsrep-cluster-name=NextcloudCluster
          --innodb-flush-log-at-trx-commit=2
          --max_allowed_packet=128M
          --skip_name_resolve=1
          --innodb_buffer_pool_size=128M
          --innodb_buffer_pool_instances=1
          --innodb_log_buffer_size=32M
          --innodb_max_dirty_pages_pct=90
          --query_cache_type=1
          --query_cache_limit=2M
          --query_cache_min_res_unit=2k
          --query_cache_size=64M
          --tmp_table_size=64M
          --max_heap_table_size=64M
          --slow_query_log=1
          --long_query_time=1
          --wait_timeout=30
          --wsrep-node-name=nc-db02 
          --wsrep-node-address="172.24.0.101"
    restart: always
    env_file:
      - db.env
    volumes:
      - './db02-data:/var/lib/mysql'
    networks:
      nextcloud:
        ipv4_address: 172.24.0.101

networks:
  nextcloud:
    external: true
    name: nextcloud
    driver: overlay

volumes:
  nextcloud:
  nc-sqlbroker:
      
      


