version: "3.8"
services:

  app:
    image: ni-nextcloud-fpm:version

  fpm01:
    image: ni-nextcloud-fpm:version

  fpm02:
    image: ni-nextcloud-fpm:version


  fpm03:
    image: ni-nextcloud-fpm:version

  fpm04:
    image: ni-nextcloud-fpm:version






